services:
  api:
    build:
      context: ../backend
      dockerfile: InteractHub.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:5073"
      # SỬA Ở ĐÂY: Dùng host.docker.internal để kết nối với container DB đang chạy bên ngoài
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=InteractHubDb;User Id=sa;Password=Kh1227102005@*;TrustServerCertificate=True"
      Jwt__Key: "YOUR_LONG_SECRET_KEY_MIN_32_CHARACTERS_REQUIRED"
      Jwt__Issuer: "InteractHub"
      Jwt__Audience: "InteractHubClient"
      Jwt__ExpireMinutes: "60"
    ports:
      - "127.0.0.1:5073:5073"
    container_name: interacthub-api
    networks:
      - interacthub-network
    restart: unless-stopped

  web:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://api:5073
    ports:
      - "127.0.0.1:3000:80"
    depends_on:
      - api
    container_name: interacthub-web
    networks:
      - interacthub-network
    restart: unless-stopped

networks:
  interacthub-network:
    driver: bridge