version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    container_name: interacthub-sql

  api:
    build:
      context: ../backend/InteractHub.Api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=InteractHubDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True
      - Jwt__Key=YOUR_LONG_SECRET_KEY
      - Jwt__Issuer=InteractHub
      - Jwt__Audience=InteractHubClient
      - Jwt__ExpireMinutes=60
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver

  web:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - api